name: product-catalog-CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the code
        uses: actions/checkout@v4

      - name: Setup Go 1.22
        uses: actions/setup-go@v2
        with:
          go_version: 1.22

      - name: Build the code
        runs: |
          cd src/product-catalog
          go mod download
          go build -o product-catalog-service main.go

      - name: Tests
        runs: |
          cd src/product-catalog
          go test ./...

  docker:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: checkout the code
        uses: actions/checkout@v4

      - name: Install the docker
        uses: docker/setup-buildx-action@v1

      - name: Login to docker
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}

      - name: Docker build and push the image
        uses: docker/build-push-action@v6
        with:
          context: src/product-catalog
          file: src/product-catalog/Dockerfile
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/product-catalog:${{github.run_id}}

  update K8s:
    runs-on: ubuntu-latest

    needs: docker

    steps:
      - name: checkout the code
        uses: actions/checkout@v4
        with:
          token: ${{secrets.GITHUB_TOKEN}}

      - name: update the deployment
        run: |
          sed -i "s|image: .*|image: ${{secrets.DOCKER_USERNAME}}/product-catalog:${{github.run_id}}|" kubernetes/productcatalog/deploy.yaml

      - name: Push and commit the git repo
        run: |
          git config --global user.email "aayushrathi47@gmail.com"
          git config --global user.name "Aayush Rathi"
          git add kubernetes/productcatalog/deploy.yaml
          git commit -m "Updated the productCatalogDeployment"
          git push origin HEAD:main -f
